include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/models/**/*.freezed.dart
    - lib/src/models/**/*.g.dart
  errors:
    invalid_use_of_visible_for_testing_member: error
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
