name: dooz_gateway_sdk
description: A Dart SDK to interact with DooZ ooPLA product (IP-BT gateway) and enable control over DooZ mesh n/w
version: 0.4.0
homepage: https://www.dooz-domotique.com/
repository: https://github.com/OZEO-DOOZ/dooz_gateway_sdk
issue_tracker: https://github.com/OZEO-DOOZ/dooz_gateway_sdk/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_rpc_2: ^3.0.1
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0
  pedantic: ^1.11.1
  freezed_annotation: ^1.1.0

dev_dependencies:
  test: ^1.20.2
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
