name: dooz_gateway_sdk
description: A Dart SDK to interact with DooZ ooPLA product (IP-BT gateway) and enable control over DooZ mesh n/w
version: 0.2.3
homepage: https://www.dooz-domotique.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_rpc_2: ^3.0.1
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0
  pedantic: ^1.11.0
  freezed_annotation: ^0.14.3

dev_dependencies:
  test: ^1.17.10
  build_runner: ^2.1.0
  freezed: ^0.14.4
  json_serializable: ^5.0.0
